name: dump
description: dump contexts

runs:
  using: "composite"
  steps:
    - name: github
      env:
        current_step: github
      run: |
        echo '${{ env.current_step }}'
        echo '${{ toJson(github) }}' | TERM=xterm jq --color-output .
      shell: bash

    - name: env
      env:
        current_step: env
      run: |
        echo '${{ env.current_step }}'
        echo '${{ toJson(env) }}' | TERM=xterm jq --color-output .
      shell: bash

    - name: vars
      env:
        current_step: vars
      run: |
        echo '${{ env.current_step }}'
        echo '${{ toJson(vars) }}' | TERM=xterm jq --color-output .
      shell: bash

    - name: runner
      env:
        current_step: runner
      run: |
        echo '${{ env.current_step }}'
        echo '${{ toJson(runner) }}' | TERM=xterm jq --color-output .
      shell: bash

    - name: job
      env:
        current_step: job
      run: |
        echo '${{ env.current_step }}'
        echo '${{ toJson(job) }}' | TERM=xterm jq --color-output .
      shell: bash

