# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions
name: dump
description: dump contexts

runs:
  using: "composite"
  shell: bash
  steps:
    - name: dump/github
      env:
        current_step: github
        BASH_ENV: "${{ github.workspace }}/bash_env.sh"
      run: |
        set -Eeuo pipefail
        context github '${{ toJson(github) }}'

    - name: dump/env
      env:
        current_step: env
        BASH_ENV: "${{ github.workspace }}/bash_env.sh"
      run: |
        set -Eeuo pipefail
        context env '${{ toJson(env) }}'

    # - name: vars
    #   env:
    #     current_step: vars
    #   shell: bash
    #   if: ${{ fromJSON(toJSON(vars)) != {} }}
    #   run: |
    #     echo '${{ env.current_step }}'
    #     echo '${{ toJson(vars) }}' | TERM=xterm jq --color-output .
    
    - name: dump/runner
      env:
        current_step: runner
        BASH_ENV: "${{ github.workspace }}/bash_env.sh"
      run: |
        set -Eeuo pipefail
        context runner '${{ toJson(runner) }}'

    - name: dump/job
      env:
        current_step: job
        BASH_ENV: "${{ github.workspace }}/bash_env.sh"
      run: |
        set -Eeuo pipefail
        context job '${{ toJson(job) }}'

