# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions
name: dump
description: dump contexts

runs:
  using: "composite"
  steps:
    - name: dump/github
      shell: bash
      env:
        current_step: github
        BASH_ENV: "${{ github.workspace }}/bash_env.sh"
      run: |
        set -Eeuo pipefail
        context github '${{ toJson(github) }}'

    - name: dump/env
      shell: bash
      env:
        current_step: env
        BASH_ENV: "${{ github.workspace }}/bash_env.sh"
      run: |
        set -Eeuo pipefail
        context env '${{ toJson(env) }}'

    - name: dump/vars
      if: ${{ fromJSON(toJSON(var)) != {} }}
      shell: bash
      env:
        current_step: vars
        BASH_ENV: "${{ github.workspace }}/bash_env.sh"
      run: |
        set -Eeuo pipefail
        context var '${{ toJson(var) }}'
    
    - name: dump/runner
      shell: bash
      env:
        current_step: runner
        BASH_ENV: "${{ github.workspace }}/bash_env.sh"
      run: |
        set -Eeuo pipefail
        context runner '${{ toJson(runner) }}'

    - name: dump/job
      shell: bash
      env:
        current_step: job
        BASH_ENV: "${{ github.workspace }}/bash_env.sh"
      run: |
        set -Eeuo pipefail
        context job '${{ toJson(job) }}'

