# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions
name: dump
description: dump contexts

runs:
  using: "composite"
  env:
    current_action: dump
  shell: bash
  steps:
    - name: ${{ env.current_action }}/github
      env:
        current_step: github
      run: |
        set -Eeuo pipefail
        context github '${{ toJson(github) }}'

    - name: env
      env:
        current_step: env
      run: |
        set -Eeuo pipefail
        context env '${{ toJson(env) }}'

    # - name: vars
    #   env:
    #     current_step: vars
    #   shell: bash
    #   if: ${{ fromJSON(toJSON(vars)) != {} }}
    #   run: |
    #     echo '${{ env.current_step }}'
    #     echo '${{ toJson(vars) }}' | TERM=xterm jq --color-output .
    
    - name: runner
      env:
        current_step: runner
      run: |
        set -Eeuo pipefail
        context env '${{ toJson(env) }}'

    - name: job
      env:
        current_step: job
      run: |
        set -Eeuo pipefail
        context env '${{ toJson(env) }}'

