# gh workflow run --workflow=launch.yaml --field entry=${name} --field args="one two three four"
# bin/wf.run launch.yaml -f entry=${name} -f args="one two three four"

name: launch
on:
  # gh workflow run --workflow=launch.yaml
  workflow_dispatch:
    inputs:
      # --field entry=${name}
      entry:
        description: "inputs.entry, a relative script pathname"
        required: false
        default: echo
      # --field args="one two three four"
      args:
        description: "entry point args"
        required: false
        default: ''

defaults:
  run:
     # set -Eeuo pipefail, note that --init-file ${file} is NOT honored
     # shell: bash -Eueo pipefail -x -- {0}
     shell: bash -Eeuo pipefail -- {0}

jobs:
  launch-job:
    runs-on: ubuntu-latest
    env:
      current_job: launch-job
      BUILD_ROOT: "${{ github.workspace }}"
      # (indirectly) sourced before each step
      BASH_ENV: "${{ github.workspace }}/bash_env.sh"
    steps:
      # get the code
      - uses: actions/checkout@v4

      # launch a script
      - run: |
          echo '${{ env.header }}'
          ${{ inputs.entry }} ${{ inputs.args }}
        env:
           current_step: launch
           header: '${{ env.current_job}}/${{ env.current_step}}'
          
      # report the exit status
      - run: |
          echo "${{ env.header }}: ${{ job.status }}"
        env:
          current_step: EXIT
          header: '${{ env.current_job}}/${{ env.current_step}}'
        if: always()
        
