# gh workflow run --workflow=start.yaml
# bin/wf.run start.yaml
name: start

on:
  # allows gh workflow run
  workflow_dispatch:
  push:

defaults:
  run:
     # set -Eeuo pipefail, note that --init-file ${file} is NOT honored
     # shell: bash -Eueo pipefail -x -- {0}
     shell: bash -Eeuo pipefail -- {0}

jobs:
  start-job0:
    runs-on: ubuntu-latest
    env:
      current_job: start-job0
      BUILD_ROOT: "${{ github.workspace }}"
      # (indirectly) sourced before each step
      BASH_ENV: "${{ github.workspace }}/bash_env.sh"
    steps:
      - name: ${{ env.current_job }}/checkout
        env:
          current_step: checkout
        uses: actions/checkout@v4

      - name: ${{ env.current_job }}/dump
        env:
          current_step: dump
        uses: ./.github/actions/dump

      # contexts: github env vars job steps runner secrets strategy matrix needs inputs
      - name: ${{ env.current_job }}/contexts
        env:
          current_step: contexts
        run: |
          context github '${{ toJSON(github) }}'
          context env '${{ toJSON(env) }}'
          context vars '${{ toJSON(vars) }}'
          context job '${{ toJSON(job) }}'
          context steps '${{ toJSON(steps) }}'
          context runner '${{ toJSON(runner) }}'
          context secrets '${{ toJSON(secrets) }}'
          context strategy '${{ toJSON(strategy) }}'
          context matrix '${{ toJSON(matrix) }}'
          context needs '${{ toJSON(needs) }}'
          context inputs '${{ toJSON(inputs) }}'

      - name: ${{ env.current_job }}/tree
        env:
          current_step: tree
        run: |
          tree ${PWD}

      - name: ${{ env.current_job }}/EXIT
        env:
          current_step: EXIT
        if: always()
        run: |
          echo "${{ env.current_step }}: ${{ job.status }}"
